name: Using Matrix
on: push

jobs:
  deploy:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, whalesay]
        # exclude:
        #   - images: alpine
        #     os: windows-latest
        # include:
        #   - images: amd64/alpine
        #     os: ubuntu-latest

    runs-on: ${{matrix.os}}
    steps:
      - name: Docker Run ${{matrix.images}}
        run: docker run ${{matrix.images}}
